INSERT INTO tb_genero
	(nome)
VALUES
	('Samba'),
	('Bossa Nova'),
	('MPB - Música Popular Brasileira'),
	('Forró'),
	('Axé'),
	('Pagode'),
	('Funk carioca'),
	('Choro'),
	('Frevo'),
	('Maracatu'),
	('Baião'),
	('Música sertaneja'),
	('Gospel'),
	('Rock brasileiro'),
	('Rap brasileiro'),
	('Música clássica brasileira'),
	('Jazz brasileiro'),
	('Música eletrônica brasileira'),
	('Sertanejo universitário'),
	('Funk ostentação'),
	('Tecnobrega'),
	('Lundu'),
	('Moda de viola'),
	('Carimbó'),
	('Ciranda'),
	('Coco'),
	('Jongo'),
	('Maxixe'),
	('Música caipira'),
	('Música gaúcha'),
	('Música nativista'),
	('Música crioula'),
	('Música afro-brasileira'),
	('Música instrumental brasileira'),
	('Música folclórica brasileira'),
	('Samba-reggae'),
	('Samba-enredo'),
	('Samba-rock'),
	('Tropicália'),
	('Baião de dois'),
	('Frevo de bloco'),
	('Frevo-canção'),
	('Marcha-rancho'),
	('Marchinhas de carnaval'),
	('Samba de coco'),
	('Samba de roda'),
	('Reggae brasileiro'),
	('Rock alternativo brasileiro'),
	('Rock progressivo brasileiro'),
	('Música erudita contemporânea brasileira'),
	('Música experimental brasileira'),
	('Música infantil brasileira'),
	('Música para dançar'),
	('Música para ouvir'),
	('Sertanejo raiz'),
	('Sertanejo romântico'),
	('Música gospel contemporânea'),
	('Música cristã brasileira'),
	('Música católica brasileira'),
	('Música popular nordestina');