CREATE DATABASE IF NOT EXISTS db_familia
COLLATE utf8mb4_general_ci 
CHARSET utf8mb4;

USE db_familia;

CREATE TABLE IF NOT EXISTS tb_pai (
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL
)AUTO_INCREMENT = 1; 

CREATE TABLE IF NOT EXISTS tb_mae (
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL
)AUTO_INCREMENT = 1; 


CREATE TABLE IF NOT EXISTS tb_filho (
	id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    id_pai INT NOT NULL,
    id_mae INT NOT NULL,
CONSTRAINT fk_id_pai FOREIGN KEY (id_pai) REFERENCES tb_pai (id),
CONSTRAINT fk_id_mae FOREIGN KEY (id_mae) REFERENCES tb_mae (id)
)AUTO_INCREMENT = 1; 








